# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WeaveLabs Software Solutions | Web and Mobility Solutions
email: hello@weavelabs.com
description: > # this means to ignore newlines until "baseurl:"
  We are a team of professional software engineers and architects,
  who build end-to-end solutions for you. Using agile software engineering
  principles, we work in short sprints to deliver impactful software in every
  iteration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://weavelabs.com" # the base hostname & protocol for your site
twitter_username: weavelabs
github_username:  weavelabs

# Build settings
markdown: kramdown
