# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WeaveLabs | We build web and mobile solutions
email: hello@weavelabs.com
description: > # this means to ignore newlines until "baseurl:"
  Team of professional software engineers and architects, who build web and mobile solutions.
  We work in short sprints to deliver impactful software in every iteration.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://weavelabs.com" # the base hostname & protocol for your site
twitter_username: weavelabs
github_username:  weavelabs
og_image: https://weavelabs.com/images/logo_full.png

# Build settings
markdown: kramdown
